Repository Fermented-Software/Kimchi, pull requests merged in 2022-09, with the labels that each got.

#2 Add docker
  .gitignore
  Dockerfile
  README.md
  bin/rails
  bin/rake
  docker-compose.yml
  entrypoint.sh
Labels: enhancement

#9 feat: initial github actions config
  .github/workflows/ci-release.yaml
  .github/workflows/pr-test.yaml
Labels: enhancement

#8 feat: implement code climate
  README.md
Labels: enhancement

#12 feat: add ga badges
  README.md
Labels: question

#18 fix: allow heroku dns
  Dockerfile
  config/environments/development.rb
Labels: bug

#14 doc: adds members names to the README
  README.md
Labels: documentation

#16 fix: Use github actions to publish test coverage to coveralls
  .github/workflows/build-and-test.yaml
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  lib/math.rb
  spec/math_spec.rb
  spec/spec_helper.rb
  test/test_helper.rb
Labels: enhancement

#19 Closing iteration 0
  .github/workflows/build-and-test.yaml
  .github/workflows/heroku-deploy.yml
  .gitignore
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  config/environments/development.rb
  lib/math.rb
  spec/math_spec.rb
  spec/spec_helper.rb
  test/test_helper.rb
Labels: documentation, enhancement
